Support new logging API introduced in Crystal 0.35.1
calebuharrison/faktory.cr pull request #4
Opened 2021-05-08 23:24 UTC by imcrazytwkr

Should close issue #3

2021-05-08 23:46 UTC, imcrazytwkr commented
@emanzx, do you have any code we can test this PR with?
Looks like it should work and crystal formatter is happy but since there's no tests, there's also no guarantee. I migrated all of my workers to the official Go implementation back in 2019 and no longer have anything that uses this library.

2025-10-07 18:23 UTC, hugopl requested changes

2025-10-07 18:23 UTC, hugopl commented on src/faktory_worker.cr
> +      Log.fatal("Missing FAKTORY_PROVIDER environment variable")
Must use a block on log.

```suggestion
      Log.fatal { "Missing FAKTORY_PROVIDER environment variable" }
```

2025-11-16 13:18 UTC, imcrazytwkr commented
@hugopl this PR has been opened over 4 years ago to fix compatibility with 0.35.x branch. I have neither energy, nor interest to update the code for this library atm. I haven't been working with Fakroty since 2023 either so I can't guarantee that even after all the fixes it's going to end up being compatible with current mainline API either. Feel free to take any the changes from this PR ([branch ref](https://github.com/imcrazytwkr/faktory_worker_crystal/tree/hotfix/support-modern-crystal)) you want and base your own updates off of it.

Asking for maintainer-level access from the repo owner or forking the project under a different name would probably be your best bet if you want to seriously use the library.

2025-11-16 13:21 UTC, imcrazytwkr commented
Closing this PR since #3 has been clearly superceded by #5 and I'm in no position to handle #5 atm.

2025-11-16 13:21 UTC, closed without merging